title: CAW Lerntagebuch
author: Marvin Karhan, Nathalie Sauer, Joel Staubach
# email: marvin.karhan@stud.hs-mannheim.de
description: > # this means to ignore newlines until "baseurl:"
  Lerntagebuch im Modul Campusmanagement als Applikationskontext für Webanwendungen

# social links
# github_username:  marvinkarhan # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
