title: CAW Lerntagebuch
author: Marvin Karhan
email: marvin.karhan@stud.hs-mannheim.de
description: > # this means to ignore newlines until "baseurl:"
  Vorlage für ein Lerntagebuch im Kurs Bibliotheks- und Archivinformatik FS2020

# social links
github_username:  marvinkarhan # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
